[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base="light"
primaryColor="#003366"
backgroundColor="#F7F7F7"
secondaryBackgroundColor="#E8ECF2"
textColor="#1A1A1A"
font="serif"

